### ISSUE TITLE
Error: spawn yarnpkg ENOENT (windows)

### ISSUE THREAD

**Issue by janat08** [sysgears/create-apollo-app#54]
```
Error: spawn yarnpkg ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
error Command failed.
```
yarnpkg exists and in path. I believe i saw stackoverflow adress the issue on windows (if youre author)

**Comment by vlasenko** [comment]
@janat08 Hmm, strange, I'll check. Could you remember that stackoverflow answer link?

**Comment by janat08** [comment]
https://stackoverflow.com/questions/43230346/error-spawn-npm-enoent

**Comment by vlasenko** [comment]
@janat08 Thank you! I'm working on it

**Comment by vlasenko** [comment]
@janat08 I'm facing other issue under Windows after this fix, I'm going to fix in tomorrow morning. Stay tuned

**Comment by vlasenko** [comment]
@janat08 I have faced an issue with broken `parse` with custom tags introduced in `mustache@2.3.1` . I have downgraded to `mustache@2.3.0` in `create-apollo-app@0.0.20` and now app generation works properly under Windows 7 for me.
