### ISSUE TITLE
using npm library in babelrc

### ISSUE THREAD

**Issue by janat08** [sysgears/create-apollo-app#55]
trying to 
.babelrc plugins:   
    ["transform-react-jsx", {
         "pragma": "Snabbdom.createElement"
       }]

Snabbdom coming from:     "snabbdom-pragma": "^2.7.0", and it says it's not found. I tried installing in on client and including babelrc in there. I suspect I should react webpack docs?

**Comment by vlasenko** [comment]
@janat08 I'm not sure I follow, which template are you using and what modifications did you made to the template exactly?

**Comment by janat08** [comment]
Universal only because I can't use this library. I'm trying to have non-default library parse jsx, so I passed:
```
["transform-react-jsx", {
"pragma": "Snabbdom.createElement"
}]
```
in plugins section of babel. Installing snabbdom-pragma library.

**Comment by vlasenko** [comment]
@janat08 Can you copy past full error stack trace from terminal?

**Comment by vlasenko** [comment]
@janat08 One more thing - where do you want to use snabdom-pragma - in TypeScript files, or in ES6 `jsx` files, .babelrc need to be tweaked for `jsx` files. But if you are using it in `tsx` files, you need to modify `tsconfig.json`

**Comment by janat08** [comment]
Otherwise the trace is:
```
C:\Users\user\dev\apollo-universal-starter-kit-master\packages\client\src\modules\subscription\containers\Subscription.js:2
import { graphql, compose } from 'react-apollo';
^
ReferenceError: Snabbdom is not defined
    at Object.../client/src/modules/i18n/index.web.js (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\client\src\modules\subscription\containers\Subscription.js:2:1)
    at __webpack_require__ (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\client\src\modules\common\components\web\ui-bootstrap\components\LanguagePicker.jsx:28:1)
    at fn (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\client\src\modules\common\components\clientOnly.jsx:4:1)
    at Object.../client/src/modules/index.js (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\client\src\modules\subscription\containers\Subscription.js:33:1)
    at __webpack_require__ (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\client\src\modules\common\components\web\ui-bootstrap\components\LanguagePicker.jsx:28:1)
    at fn (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\client\src\modules\common\components\clientOnly.jsx:4:1)
    at Object.../common/createReduxStore.js (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\server\build\index.js:20873:78)
    at __webpack_require__ (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\client\src\modules\common\components\web\ui-bootstrap\components\LanguagePicker.jsx:28:1)
    at fn (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\client\src\modules\common\components\clientOnly.jsx:4:1)
    at Object../src/middleware/website.jsx (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\server\build\index.js:21801:84)
    at __webpack_require__ (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\client\src\modules\common\components\web\ui-bootstrap\components\LanguagePicker.jsx:28:1)
    at fn (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\client\src\modules\common\components\clientOnly.jsx:4:1)
    at Object../src/app.js (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\server\build\index.js:21339:78)
    at __webpack_require__ (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\client\src\modules\common\components\web\ui-bootstrap\components\LanguagePicker.jsx:28:1)
    at fn (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\client\src\modules\common\components\clientOnly.jsx:4:1)
    at Object../src/server.js (C:\Users\user\dev\apollo-universal-starter-kit-master\packages\server\build\index.js:28072:63)
server-webpack info Backend has been stopped
```

**Comment by vlasenko** [comment]
@janat08 Thank you for the info!

**Comment by vlasenko** [comment]
@janat08 Looks like this stack trace is from `apollo-universal-starter-kit`, not from the `create-apollo-app` though
