### ISSUE TITLE
Fresh install no matter what type of app I create gets error envelope routines unsupported

### ISSUE THREAD

**Issue by ondrovic** [sysgears/create-apollo-app#82]
Fresh install windows 10
node: v17.4.0
npm: 8.3.1
yarn: 1.22.17
```
$ zen start
zen info Version 0.1.8
clean-webpack-plugin: C:\Users\ondro\Desktop\new-apollo-app\build has been removed.
Starting type checking service...
Using 1 worker with 2048MB memory limit
zen error Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (C:\Users\ondro\Desktop\new-apollo-app\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\Users\ondro\Desktop\new-apollo-app\node_modules\webpack\lib\NormalModule.js:401:16)
    at handleParseError (C:\Users\ondro\Desktop\new-apollo-app\node_modules\webpack\lib\NormalModule.js:449:10)
    at C:\Users\ondro\Desktop\new-apollo-app\node_modules\webpack\lib\NormalModule.js:481:5
    at C:\Users\ondro\Desktop\new-apollo-app\node_modules\webpack\lib\NormalModule.js:342:12
    at C:\Users\ondro\Desktop\new-apollo-app\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\ondro\Desktop\new-apollo-app\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\ondro\Desktop\new-apollo-app\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
zen error Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (C:\Users\ondro\Desktop\new-apollo-app\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\Users\ondro\Desktop\new-apollo-app\node_modules\webpack\lib\NormalModule.js:401:16)
    at handleParseError (C:\Users\ondro\Desktop\new-apollo-app\node_modules\webpack\lib\NormalModule.js:449:10)
    at C:\Users\ondro\Desktop\new-apollo-app\node_modules\webpack\lib\NormalModule.js:481:5
    at C:\Users\ondro\Desktop\new-apollo-app\node_modules\webpack\lib\NormalModule.js:342:12
    at C:\Users\ondro\Desktop\new-apollo-app\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\ondro\Desktop\new-apollo-app\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at C:\Users\ondro\Desktop\new-apollo-app\node_modules\loader-runner\lib\LoaderRunner.js:186:6 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by mark-d-holmberg** [comment]
```
export NODE_OPTIONS='--openssl-legacy-provider'

yarn start
```
